### ISSUE TITLE
Add Support for Other Authentication Types besides User Pools

### ISSUE THREAD

**Issue by lagroujl** [awslabs/aws-dynasync#1]
AppSync supports multiple authentication types, API_KEY, AWS_LAMBDA, AWS_IAM, OPENID_CONNECT, and AMAZON_COGNITO_USER_POOLS. Currently, this solution supports only AMAZON_COGNITO_USER_POOLS. 

Currently, the public interfaces require the user to use Cognito User Pools for authentication. 

As an intermediary step, change props from

```
{
   config: UserPoolConfig
}
```
to

```
{
  authorization: AuthorizationConfig /* Comes from CDK */
}
```

Then users can reference the AWS CDK docs for configuration options, and future updates to GraphQL API authentication will not require a code change.

**Comment by smguggen** [comment]
For backward compatibility I left the `userPool` field and added an optional `auth` field to list an array of authorizationModes
